name: inception

services:
  website:
    build: ./requirements/bonus/website
    ports:
      - "3001:3000"
    volumes:
      - website-data:/var/www:rw
  minecraft:
    build: ./requirements/bonus/minecraft
    ports:
      - "25565:25565"
  ftp:
    build:
      context: ./requirements/bonus/ftp
      secrets:
        - WP_ADMIN_PASSW
    volumes:
      - wp-data:/var/wp/:rw
    ports:
      - "2121:2121"
    depends_on:
      - wordpress
    restart: always
  adminer:
    build: ./requirements/bonus/adminer
    volumes:
      - wp-data:/var/wp/:rw
    ports:
      - "8000:8000"
    networks:
      db-net:
  redis:
    build: ./requirements/bonus/redis
    networks:
      redis-net:
        aliases:
          - redis
    # ports:
    #  - '6379:6379'
  mariadb:
    # hostname: db
    build: ./requirements/mariadb
    volumes:
      - db-data:/var/db/:rw
    networks:
      db-net:
        aliases:
          - db
    secrets:
      - WP_ADMIN_LOGIN
      - WP_ADMIN_PASSW
      - WP_GUEST_LOGIN
      - WP_GUEST_PASSW
      - WP_DB_NAME
    # - type: bind
    #   source: /home/ahbasara/data/db
    #   target: /var/db
    # - /home/ahbasara/data/db:/var/db
  wordpress:
    # hostname: wp
    build: 
      context: ./requirements/wordpress
      secrets:
        - WP_ADMIN_LOGIN
        - WP_ADMIN_PASSW
        - WP_DB_NAME
        - WP_GUEST_LOGIN
        - WP_GUEST_PASSW
    depends_on:
     - mariadb

    expose:
      - "9000"
    volumes:
      - wp-data:/var/wp/:rw
    networks:
      nginx-net:
        aliases:
          - wp
      db-net:
        aliases:
          - wp_db
      redis-net:
        aliases:
          - wp
    secrets:
      - WP_DB_NAME
      - WP_ADMIN_LOGIN
      - WP_ADMIN_PASSW
      - WP_GUEST_LOGIN
      - WP_GUEST_PASSW

  nginx:
    # hostname: ng
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/wp/:rw
    depends_on:
     - wordpress
    networks:
      nginx-net:
        aliases:
          - ng
  # ftp:
  #   build: ./requirements/ftp
  #   ports:
  #     - "21:21"
  #   volumes:
  #   - wp-data:/var/wp/:rw
secrets:
  # LOGIN_42:
  #   external: true
  WP_DB_NAME:
    file: ../WP_DB_NAME
  WP_ADMIN_LOGIN:
    file: ../WP_ADMIN_LOGIN
  WP_ADMIN_PASSW:
    file: ../WP_ADMIN_PASSW
  WP_GUEST_LOGIN:
    file: ../WP_GUEST_LOGIN
  WP_GUEST_PASSW:
    file: ../WP_GUEST_PASSW
  
networks:
  nginx-net:
    driver: bridge
  db-net:
    driver: bridge
  redis-net:
    driver: bridge

volumes:
  website-data:
    name: "website-volume"
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ahbasara/data/www # ahbasara -> ${LOGIN_42}
  db-data:
    name: "db-volume"
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ahbasara/data/db # ahbasara -> ${LOGIN_42}
  wp-data:
    name: "wp-volume"
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ahbasara/data/wp # ahbasara -> ${LOGIN_42}
