name: inception

services:
  mariadb:
    # hostname: db
    build: ./requirements/mariadb
    volumes:
      - db-data:/var/db/:rw
    networks:
      db-net:
        aliases:
          - db
    # env_file: "./.env"
    environment:
    - WP_ADMIN_LOGIN=${WP_ADMIN_LOGIN}
    - WP_ADMIN_PASSW=${WP_ADMIN_PASSW}
    - WP_GUEST_LOGIN=${WP_GUEST_LOGIN}
    - WP_GUEST_PASSW=${WP_GUEST_PASSW}
    # - type: bind
    #   source: /home/ahbasara/data/db
    #   target: /var/db
    # - /home/ahbasara/data/db:/var/db
  wordpress:
    # hostname: wp
    build: ./requirements/wordpress
    expose:
      - "9000"
    volumes:
      - wp-data:/var/wp/:rw
    networks:
      nginx-net:
        aliases:
          - wp
      db-net:
        aliases:
          - wp_db
    # env_file: "./.env"
    environment:
    - WP_DB_NAME=${WP_DB_NAME}
    - WP_ADMIN_LOGIN=${WP_ADMIN_LOGIN}
    - WP_ADMIN_PASSW=${WP_ADMIN_PASSW}
  nginx:
    # hostname: ng
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/wp/:rw
    networks:
      nginx-net:
        aliases:
          - ng
  # ftp:
  #   build: ./requirements/ftp
  #   ports:
  #     - "21:21"
  #   volumes:
  #   - wp-data:/var/wp/:rw

networks:
  nginx-net:
    driver: bridge
  db-net:
    driver: bridge

volumes:
  db-data:
    name: "db-volume"
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/${LOGIN_42}/data/db
  wp-data:
    name: "wp-volume"
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/${LOGIN_42}/data/wp
