name: 1ncepti0n
# Of course, using network: host or --link or links: is forbidden.
services:
  db:
    build: ./requirements/mysql
    # ports:
    # - "8000:5000"
    volumes:
      - db-data:/var/db/:rw
    networks:
      - db-net
    # - type: bind
    #   source: /home/ahbasara/data/db
    #   target: /var/db

    # - /home/ahbasara/data/db:/var/db
  wordpress:
    build: ./requirements/wordpress
    # ports:
    #   - "9000:9000"
    expose:
      - "9000"
    volumes:
      - wp-data:/var/wp/:rw
    networks:
      - nginx-net
      - db-net
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wp-data:/var/wp/:rw
    networks:
      - nginx-net
  ftp:
    build: ./requirements/ftp
    ports:
      - "21:21"
    volumes:
    - wp-data:/var/wp/:rw

networks:
  nginx-net:
    driver: bridge
  db-net:
    driver: bridge

volumes:
  db-data:
    name: "db-volume"
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ahbasara/data/db
  wp-data:
    name: "wp-volume"
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ahbasara/data/wp
