cat > setup.sql <<EOF
CREATE DATABASE wp;
CREATE USER "$WP_ADMIN_LOGIN"@"hostname" IDENTIFIED BY "$WP_ADMIN_PASSWD";
GRANT ALL PRIVILEGES ON wp.* TO "$WP_ADMIN_LOGIN"@"hostname";
CREATE USER "$WP_LOGIN"@"hostname" IDENTIFIED BY "$WP_PASSWD";
GRANT ALL PRIVILEGES ON wp.* TO "$WP_LOGIN"@"hostname";
FLUSH PRIVILEGES;
EXIT;
EOF