db_ip=$(getent hosts db | awk '{ print $1 }')
wp_ip=$(getent hosts wp_db | awk '{ print $1 }')

cat <<EOF
CREATE DATABASE wp;
CREATE USER "$WP_ADMIN_LOGIN"@"%" IDENTIFIED BY "$WP_ADMIN_PASSW";
GRANT ALL PRIVILEGES ON wp.* TO "$WP_ADMIN_LOGIN"@"%";
CREATE USER "$WP_GUEST_LOGIN"@"%" IDENTIFIED BY "$WP_GUEST_PASSW";
GRANT ALL PRIVILEGES ON wp.* TO "$WP_GUEST_LOGIN"@"%";
FLUSH PRIVILEGES;
EOF