db_ip=$(getent hosts db | awk '{ print $1 }')
wp_ip=$(getent hosts wp_db | awk '{ print $1 }')

WP_ADMIN_LOGIN=`cat /run/secrets/WP_ADMIN_LOGIN`
WP_ADMIN_PASSW=`cat /run/secrets/WP_ADMIN_PASSW`
WP_GUEST_LOGIN=`cat /run/secrets/WP_GUEST_LOGIN`
WP_GUEST_PASSW=`cat /run/secrets/WP_GUEST_PASSW`
WP_DB_NAME=`cat /run/secrets/WP_DB_NAME`

cat <<EOF
CREATE DATABASE IF NOT EXISTS $WP_DB_NAME;
CREATE USER IF NOT EXISTS "$WP_ADMIN_LOGIN"@"%" IDENTIFIED BY "$WP_ADMIN_PASSW";
GRANT ALL PRIVILEGES ON wp.* TO "$WP_ADMIN_LOGIN"@"%";
CREATE USER "$WP_GUEST_LOGIN"@"%" IDENTIFIED BY "$WP_GUEST_PASSW";
GRANT ALL PRIVILEGES ON wp.* TO "$WP_GUEST_LOGIN"@"%";
FLUSH PRIVILEGES;
EOF
